baseURL = "https://yrjkqq.github.io/"
languageCode = "en-us"
title = "That's the Way It Is"
# theme = "ananke"
theme = "archie"
publishDir = "docs"
copyright = "© yrjkqq"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  mode = "auto"
  useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
  favicon = "/img/favicon.ico"
  site_logo = "/img/favicon.ico"

# Main menu Items

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 1