baseURL = "https://yrjkqq.github.io/posts/"
languageCode = "en-us"
title = "That's the Way It Is"
theme = "ananke"
publishDir = "docs"

[params]
  favicon = "img/favicon.ico"
  site_logo = "/posts/img/favicon.ico"
  post_content_classes = "sans-serif bg-near-white"